chore: initial version (#6)
* chore: bump docker/login-action from 2 to 3

Bumps [docker/login-action](https://github.com/docker/login-action) from 2 to 3.
- [Release notes](https://github.com/docker/login-action/releases)
- [Commits](https://github.com/docker/login-action/compare/v2...v3)

---
updated-dependencies:
- dependency-name: docker/login-action
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore: bump docker/build-push-action from 4 to 5

Bumps [docker/build-push-action](https://github.com/docker/build-push-action) from 4 to 5.
- [Release notes](https://github.com/docker/build-push-action/releases)
- [Commits](https://github.com/docker/build-push-action/compare/v4...v5)

---
updated-dependencies:
- dependency-name: docker/build-push-action
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore: bump docker/setup-buildx-action from 2 to 3

Bumps [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) from 2 to 3.
- [Release notes](https://github.com/docker/setup-buildx-action/releases)
- [Commits](https://github.com/docker/setup-buildx-action/compare/v2...v3)

---
updated-dependencies:
- dependency-name: docker/setup-buildx-action
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore: bump wagoid/commitlint-github-action from 5.3.1 to 5.4.4

Bumps [wagoid/commitlint-github-action](https://github.com/wagoid/commitlint-github-action) from 5.3.1 to 5.4.4.
- [Changelog](https://github.com/wagoid/commitlint-github-action/blob/master/CHANGELOG.md)
- [Commits](https://github.com/wagoid/commitlint-github-action/compare/v5.3.1...v5.4.4)

---
updated-dependencies:
- dependency-name: wagoid/commitlint-github-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore: bump stefanzweifel/git-auto-commit-action from 4 to 5

Bumps [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) from 4 to 5.
- [Release notes](https://github.com/stefanzweifel/git-auto-commit-action/releases)
- [Changelog](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/CHANGELOG.md)
- [Commits](https://github.com/stefanzweifel/git-auto-commit-action/compare/v4...v5)

---
updated-dependencies:
- dependency-name: stefanzweifel/git-auto-commit-action
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* build: adding dockerfile

* style: lint fix

* style: actions lint fix

* ci: run on ubuntu-latest

* style: action lint fixes

* ci: move workflow linting to super linter

* ci: move workflow linting to super linter

* style: action lint fixes

* style: action lint fixes

* ci: replace pr labels with new workflow code

* ci: replace pr title check action with custom code

* ci: flux auto release tags for container

* fix: f-string issue

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,13 +2,15 @@ name: 'CI'
 
 on:
   push:
-    branches: ['**']
-    tags: ['**']
+    branches:
+      - '**'
+    tags:
+      - '**'
 
 jobs:
   lint:
     name: 'Lint'
-    runs-on: 'ubuntu-20.04'
+    runs-on: 'ubuntu-latest'
     steps:
       - uses: 'actions/checkout@v3'
       - uses: 'actions/setup-python@v4'
@@ -22,31 +24,32 @@ jobs:
           pip install -r requirements.txt
       - name: 'Flake8 :allthethings:'
         run: 'python -m flake8 --max-line-length 120'
-#  test:
-#    name: 'Test'
-#    runs-on: 'ubuntu-20.04'
-#    steps:
-#      - uses: 'actions/checkout@v3'
-#      - uses: 'actions/setup-python@v4'
-#        with:
-#          python-version: '3.11'
-#      - name: 'Install dependencies'
-#        run: |
-#          echo "Installing CI requirements"
-#          pip install --upgrade --user pip pytest coverage pyfakefs
-#          echo "Installing project requirements"
-#          pip install -r requirements.txt
-#      - name: 'Run tests'
-#        run: 'python -m coverage run --branch -m pytest'
-#      - name: 'Display coverage report'
-#        run: |
-#          python -m coverage report --fail-under=80 \
-#          --omit="*/.local/*","*/tests/test_*" -m
+  #  test:
+  #    name: 'Test'
+  #    runs-on: 'ubuntu-latest'
+  #    steps:
+  #      - uses: 'actions/checkout@v3'
+  #      - uses: 'actions/setup-python@v4'
+  #        with:
+  #          python-version: '3.11'
+  #      - name: 'Install dependencies'
+  #        run: |
+  #          echo "Installing CI requirements"
+  #          pip install --upgrade --user pip pytest coverage pyfakefs
+  #          echo "Installing project requirements"
+  #          pip install -r requirements.txt
+  #      - name: 'Run tests'
+  #        run: 'python -m coverage run --branch -m pytest'
+  #      - name: 'Display coverage report'
+  #        run: |
+  #          python -m coverage report --fail-under=80 \
+  #          --omit="*/.local/*","*/tests/test_*" -m
   container_build:
     name: 'Build and Push Docker Container'
-    runs-on: 'ubuntu-20.04'
-#    needs: ['lint', 'test']
-    needs: ['lint']
+    runs-on: 'ubuntu-latest'
+    #    needs: ['lint', 'test']
+    needs:
+      - 'lint'
     steps:
       - uses: 'actions/checkout@v3'
       - name: 'Get calculated next version based on commit history'
@@ -59,49 +62,76 @@ jobs:
           dry_run: 'true'
           append_to_pre_release_tag: 'rc-${{ github.run_id }}'
           pre_release_branches: '^((main(?!$)).+|(?!main).+)$'
-      - name: 'Prepare'
-        id: 'prep'
+      - name: Build Preparation
+        id: prep
         run: |
-          DOCKER_IMAGE=${{ github.repository }}
-          VERSION=edge
-          if [[ $GITHUB_REF == refs/tags/* ]]; then
-            VERSION=${GITHUB_REF#refs/tags/}
-          fi
-          if [[ $GITHUB_REF == refs/heads/* ]]; then
-            VERSION=${GITHUB_REF#refs/heads/}
-            if [[ $VERSION == main ]]; then
-              VERSION=latest
+          set -o nounset
+          set -e
+
+          if [[ $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            DOCKER_TAG=${GITHUB_REF#refs/tags/}
+            BRANCH=$DOCKER_TAG  # In lieu of an actual branch name
+
+            # We're building a Git release tag.  Deploy to the "main" stack.
+            STACK_SUFFIX_OVERRIDE="main"
+          elif [[ $GITHUB_REF == refs/heads/* ]]; then
+            BRANCH=${GITHUB_REF#refs/heads/}
+            if [[ $BRANCH == main ]]; then
+              # Publish a "latest" image, which may be useful to someone
+              # who doesn't care about exact versions.  Builds on "main" won't be
+              # auto-deployed and won't use this tag.  (Builds on "main" will trigger
+              # an auto-release, generating a new tag whose build will deploy to
+              # the main stack.)
+              DOCKER_TAG=latest
             else
-              VERSION=${{ steps.calculated-next-version.outputs.new_tag }}
+              BRANCH=${BRANCH#deploy-}  # Remove deploy- prefix, if any
+              DOCKER_TAG=${{ steps.calculated-next-version.outputs.new_tag }}
             fi
+
+            # Branch build; let the stack name use the normal convention.
+            STACK_SUFFIX_OVERRIDE=""
+          else
+            echo "Unexpected ref '$GITHUB_REF'.  Exiting." >&2
+            exit 1
           fi
+
           PUSH=true
           if [[ $GITHUB_REF == refs/heads/dependabot* ]]; then
             echo "Dependabot branch"
             PUSH=false
           fi
-          TAGS="${DOCKER_IMAGE}:${VERSION//\//-}"
-          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
-          echo "version=${VERSION//\//-}" >> $GITHUB_OUTPUT
-          echo "push=${PUSH}" >> $GITHUB_OUTPUT
+
+          GH_REPONAME=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
+          GH_REPO_NAME=${GH_REPONAME##*/}
+
+          {
+              echo "gh-repo-name=${GH_REPO_NAME}"
+              echo "docker-tag=${DOCKER_TAG}"
+              echo "push=${PUSH}"
+              echo "branch=${BRANCH}"
+              echo "stack-suffix-override=${STACK_SUFFIX_OVERRIDE}"
+          } >>"$GITHUB_OUTPUT"
+        env:
+          GITHUB_RUN_ID: '${{ github.run_id }}'
+          GITHUB_REPOSITORY: '${{ github.repository }}'
       - name: 'Setup Docker Buildx'
-        uses: 'docker/setup-buildx-action@v2'
+        uses: 'docker/setup-buildx-action@v3'
       - name: 'Cache Docker layers'
         uses: 'actions/cache@v3.3.1'
         with:
           path: '/tmp/.buildx-cache'
-          key: '${{ runner.os }}-buildx-${{ steps.prep.outputs.version }}'
+          key: '${{ runner.os }}-buildx-${{ steps.prep.outputs.branch }}-${{ github.sha }}'
           restore-keys: |
             ${{ runner.os }}-buildx-
-            ${{ runner.os }}-buildx-${{ steps.prep.outputs.version }}
+            ${{ runner.os }}-buildx-${{ steps.prep.outputs.branch }}
       - name: 'Login to DockerHub'
-        uses: 'docker/login-action@v2'
+        uses: 'docker/login-action@v3'
         with:
           username: 'chrisjohnson00'
           password: '${{ secrets.DOCKER_HUB_PASSWORD }}'
       - name: 'Build and push'
         id: 'docker_build'
-        uses: 'docker/build-push-action@v4'
+        uses: 'docker/build-push-action@v5'
         with:
           context: '.'
           file: './Dockerfile'
@@ -110,25 +140,31 @@ jobs:
           # publish
           push: '${{ steps.prep.outputs.push }}'
           # tags determined by prep step
-          tags: '${{ steps.prep.outputs.tags }}'
+          tags: 'chrisjohnson00/${{ steps.prep.outputs.gh-repo-name }}:${{ steps.prep.outputs.docker-tag }}'
           cache-from: 'type=local,src=/tmp/.buildx-cache'
           cache-to: 'type=local,dest=/tmp/.buildx-cache'
           labels: |
             org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
-            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
+            org.opencontainers.image.version=${{ steps.prep.outputs.branch }}
             org.opencontainers.image.source=https://github.com/${{ github.repository }}
             org.opencontainers.image.revision=${{ github.sha }}
   actionslint:
     name: 'Actions Yaml Lint'
-    runs-on: 'ubuntu-20.04'
+    runs-on: 'ubuntu-latest'
+    permissions:
+      contents: read
+      packages: read
+      # To report GitHub Actions status checks
+      statuses: write
+    env:
+      VALIDATE_YAML: true
+      VALIDATE_GITHUB_ACTIONS: true
     steps:
-      - name: 'Checkout'
-        uses: 'actions/checkout@v3'
-      - name: 'Actions Yaml Lint'
-        uses: 'karancode/yamllint-github-action@v2.1.1'
-        with:
-          yamllint_file_or_dir: '.github/workflows'
-          yamllint_comment: 'true'
-          yamllint_config_datapath: '{"extends":"default","rules":{"line-length":{"max":360,"level":"warning"},"truthy":{"check-keys":false},"document-start":{"present":false}}}'
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Super-linter
+        uses: super-linter/super-linter/slim@v5.7.2  # x-release-please-version
         env:
-          GITHUB_ACCESS_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
+          DEFAULT_BRANCH: main
+          # To report GitHub Actions status checks
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
